
# Window constants
TILE_SIZE = 32
TEXTURE_SIZE = (TILE_SIZE, TILE_SIZE)
WINDOW_SIZE = (30 * TILE_SIZE, 20 * TILE_SIZE)

MENU_IMG_SIZE = (300, 300)

# Gameplay settings
SNAKE_INIT_POS = (WINDOW_SIZE[0] // 2, WINDOW_SIZE[1] // 2)
APPLE_SPAWN_LIMIT = 3
FPS = 10

# Mappings
OBSTACLE_HASH = -1
NO_HASH = 0
HEAD_HASH = 1
APPLE_HASH = 2